### PR TITLE
added shimmer effect with css

### PR DESCRIPTION
**Pull request by AdavizeTheFirst**
Here's a demo gif
demo gif

### CODE REVIEW

**Comment by sumana2001** [comment]
Hey @AdavizeTheFirst thanks for the PR. Please share a screenshot or gif of the effect

**Comment by AdavizeTheFirst** [comment]
I have done that

**Comment by sumana2001** [comment]
Great! Thanks for the contribution😁

**Comment by sumana2001** [comment]
@all-contributors please add @Sarfraz-droid for code

**Comment by sumana2001** [comment]
@all-contributors please add @AdavizeTheFirst  for code

**Pull request merged**
