### PR TITLE
Added new menu hover effect style

### LINKED ISSUE #12: Menu Hover Effect
Check out the animation here at 0:41 https://www.youtube.com/watch?v=lnFfsP5EKf8&t=93s

ss10

Do attach screen recordings/screenshots😀

### PR DESCRIPTION
**Pull request by Dhamodhar-DDR**
Issue #12 

Added new menu hover effect style.
Added the background text.

Demo Video:
[Demo2.zip](https://github.com/sumana2001/styles/files/5347960/Demo2.zip)

Close #12

### CODE REVIEW

**Comment by sumana2001** [comment]
@Dhamodhar-DDR Hi could you also add that part where on hovering the name comes in a bigger font in the background as shown in the video link?

**Comment by Dhamodhar-DDR** [comment]
Yes, i'll do it.

**Comment by sumana2001** [comment]
@all-contributors please add @Dhamodhar-DDR  for code

**Comment by sumana2001** [comment]
Thanks! Looks great! 
Keep coding😀

**Comment by sumana2001** [comment]
Thanks! Looks great! @Dhamodhar-DDR 
Keep coding😀

**Pull request merged**
