### PR TITLE
Css 3d carousel #27

### LINKED ISSUE #27: 3D Carousel
Check out the animation here at 2:04 https://www.youtube.com/watch?v=bqfOALK0qnc

ss3

Do attach screen recordings/screenshots😀

### PR DESCRIPTION
**Pull request by pablowbk**
Currently only works for chrome. Need to find a fix for the checkbox hack in firefox

image

### CODE REVIEW

**Comment by pablowbk** [comment]
somehow, a commit from previous pr ended up here... could it be dismissed?

image

**Comment by sumana2001** [comment]
I think that commit is in your forked version so you can revert it from your side since the pr hasn't been merged yet😄 @pablowbk

**Comment by pablowbk** [comment]
Hi Sumana, could you please confirm the revert was done correctly? first time ever using this command, sorry...

**Comment by pablowbk** [comment]
the revert was leaving the commit in the PR, learnt about interactive rebase today 😄

**Comment by sumana2001** [comment]
No problem! Glad you learned😄
Happy coding!

**Pull request merged**
